IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CHOSEN_ROOMS' AND COLUMN_NAME = 'SESSION_ID')
  BEGIN

    ALTER TABLE [dbo].[Chosen_Rooms] ADD
      [SESSION_ID] VARCHAR(100)
  END