IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REQUEST' AND COLUMN_NAME = 'NR_OF_PERSON')
  BEGIN

    ALTER TABLE [dbo].[Request] ADD
      [NR_OF_PERSON] INT DEFAULT 0
  END