ALTER TABLE CUSTOMER DROP COLUMN IF EXISTS GENDER;

ALTER TABLE CUSTOMER DROP COLUMN IF EXISTS ID_NUMBER;

ALTER TABLE CUSTOMER RENAME COLUMN CUSTOMER_PHONE TO GUEST_PHONE;

ALTER TABLE CUSTOMER RENAME COLUMN CUSTOMER_EMAIL TO GUEST_EMAIL;