CREATE TABLE IF NOT EXISTS USERS (
          ID INT(10) NOT NULL PRIMARY KEY auto_increment,
          LAST_NAME VARCHAR(20) NOT NULL ,
          FIRST_NAME VARCHAR(20) NOT NULL,
          USER_ROLE VARCHAR(20) NOT NULL,
          BIRTH_DATE DATE,
          HIRE_DATE DATE NOT NULL,
          DEPARTURE_DATE DATE,
          PHONE_NUMBER INT(20),
          IMAGE_PATH VARCHAR(100),
          USER_EMAIL VARCHAR(100) NOT NULL,
          USER_PASSWORD VARCHAR(100) NOT NULL );