INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (10, 7);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (11, 7);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (12, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (13, 10);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (14, 11);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (15, 11);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (16, 10);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (17, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (18, 7);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (19, 7);

