-- IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'CUSTOMER' AND COLUMN_NAME = 'CUSTOMER_EMAIL')
--   BEGIN

    ALTER TABLE Customer ADD COLUMN IF NOT EXISTS
      CUSTOMER_EMAIL varchar(20) DEFAULT ''

--   END