CREATE TABLE ROOM_REQUEST (
          ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
          ROOM_ID INT NOT NULL,
          REQUEST_ID INT NOT NULL,
          FOREIGN KEY (ROOM_ID) REFERENCES HOTEL_ROOMS(id),
          FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST(ID) );

