CREATE TABLE ROOMS_TYPE (
          ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
          SINGLE_BED INT,
          DOUBLE_BED INT,
          NAME_ROOM VARCHAR(20),
          PRICE FLOAT);