INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (20, 3);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (21, 3);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (22, 4);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (23, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (24, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (25, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (26, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (27, 4);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (28, 3);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (29, 3);

