CREATE TABLE REQUEST (
          ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
          USER_ID INT NOT NULL,
          CUSTOMER_ID INT NOT NULL,
          REQUEST_DATE DATE NOT NULL,
          ARRIVAL_DATE DATE NOT NULL,
          DEPARTURE_DATE DATE NOT NULL,
          FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
          FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) );