CREATE TABLE IF NOT EXISTS HOTEL_ROOMS (
  ID INT(10) NOT NULL PRIMARY KEY auto_increment,
  ROOM_NUMBER INT(10) NOT NULL,
  ROOM_TYPE INT(10) NOT NULL,
  FOREIGN KEY (ROOM_TYPE) REFERENCES ROOMS_TYPE(ID) );