
    ALTER TABLE Request ADD COLUMN IF NOT EXISTS
      LATE_CHECKOUT BOOLEAN DEFAULT FALSE;

    ALTER TABLE Request ADD COLUMN IF NOT EXISTS
      LUNCH BOOLEAN DEFAULT FALSE;

    ALTER TABLE Request ADD COLUMN IF NOT EXISTS
      DINNER BOOLEAN DEFAULT FALSE
