INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (20, 9);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (21, 9);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (22, 10);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (23, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (24, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (25, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (26, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (27, 10);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (28, 9);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (29, 9);

