IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'OFFERS' AND COLUMN_NAME = 'LATE_CHECKOUT')
  BEGIN

    ALTER TABLE [dbo].[OFFERS] ADD
      [LATE_CHECKOUT] BIT DEFAULT 0
  END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'OFFERS' AND COLUMN_NAME = 'LUNCH')
  BEGIN

    ALTER TABLE [dbo].[OFFERS] ADD
      [LUNCH] BIT DEFAULT 0
  END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'OFFERS' AND COLUMN_NAME = 'DINNER')
  BEGIN

    ALTER TABLE [dbo].[OFFERS] ADD
      [DINNER] BIT DEFAULT 0
  END