IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GUEST' AND COLUMN_NAME = 'GUEST_PASSWORD')
  BEGIN

    ALTER TABLE [dbo].[Guest] ADD
      [GUEST_PASSWORD] varchar(100) DEFAULT 'parola'

  END