INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM, PRICE)
    VALUES (1,0,'Single', 50.0);

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM, PRICE)
    VALUES (0,1,'Double', 75.0);

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM, PRICE)
    VALUES (2,0,'Twin', 80.0);

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM, PRICE)
    VALUES (3,0,'Triple', 100);

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM, PRICE)
    VALUES (2,1,'Apartment1', 200.5);

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM, PRICE)
    VALUES (3,1,'Apartment2', 250.0);