
    CREATE TABLE OFFERS (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      NAME VARCHAR(20) NOT NULL ,
      DESCRIPTION VARCHAR(1000) NOT NULL ,
      START_DATE DATE NOT NULL ,
      END_DATE DATE NOT NULL,
      ROOM_TYPE INT,
      QUANTITY INT NOT NULL,
      MIN_DAYS INT,
      DISCOUNT INT NOT NULL,
      FOREIGN KEY (ROOM_TYPE) REFERENCES ROOMS_TYPE(ID) )
