ALTER TABLE CUSTOMER DROP COLUMN  GENDER;

ALTER TABLE CUSTOMER DROP COLUMN  ID_NUMBER;

ALTER TABLE CUSTOMER CHANGE `CUSTOMER_PHONE` `GUEST_PHONE` INT(11);

ALTER TABLE CUSTOMER CHANGE `CUSTOMER_EMAIL` `GUEST_EMAIL` VARCHAR(20);