
    ALTER TABLE OFFERS ADD COLUMN
      LATE_CHECKOUT BOOLEAN DEFAULT FALSE;


    ALTER TABLE OFFERS ADD COLUMN
      LUNCH BOOLEAN DEFAULT FALSE;


    ALTER TABLE OFFERS ADD COLUMN
      DINNER BOOLEAN DEFAULT FALSE
