INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (10, 1);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (11, 1);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (12, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (13, 4);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (14, 5);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (15, 5);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (16, 4);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (17, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (18, 1);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
    VALUES (19, 1);

