IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PROMOTIONS')
  BEGIN

    CREATE TABLE PROMOTIONS (
      ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
      NAME VARCHAR(20) NOT NULL ,
      DESCRIPTION VARCHAR(1000) NOT NULL ,
      ROOM_TYPE INT,
      QUANTITY INT NOT NULL,
      FOREIGN KEY (ROOM_TYPE) REFERENCES ROOMS_TYPE(ID) )

  END