INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM)
    VALUES (1,0,'Single');

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM)
    VALUES (0,1,'Double');

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM)
    VALUES (2,0,'Twin');

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM)
    VALUES (3,0,'Triple');

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM)
    VALUES (2,1,'Apartment1');

INSERT INTO ROOMS_TYPE (SINGLE_BED, DOUBLE_BED, NAME_ROOM)
    VALUES (3,1,'Apartment2');