CREATE TABLE IF NOT EXISTS ROOM_REQUEST (
          ROOM_ID INT(10) NOT NULL,
          REQUEST_ID INT(10) NOT NULL,
          FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
          FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST(ID) );

