
    ALTER TABLE Request ADD COLUMN
      LATE_CHECKOUT BOOLEAN DEFAULT FALSE;

    ALTER TABLE Request ADD COLUMN
      LUNCH BOOLEAN DEFAULT FALSE;

    ALTER TABLE Request ADD COLUMN
      DINNER BOOLEAN DEFAULT FALSE
