INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (40, 5);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (41, 5);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (42, 6);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (43, 6);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (44, 5);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (45, 5);
