CREATE TABLE IF NOT EXISTS CUSTOMER (
          ID INT(10) NOT NULL PRIMARY KEY auto_increment,
          LAST_NAME VARCHAR(20) NOT NULL ,
          FIRST_NAME VARCHAR(20) NOT NULL,
          ADDRESS VARCHAR(100),
          CNP INT(13) NOT NULL,
          GENDER VARCHAR(20),
          CUSTOMER_PHONE INT(20));



