INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (30, 7);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (31, 7);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (32, 12);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (33, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (34, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (35, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (36, 8);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (37, 10);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (38, 9);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (39, 9);

