INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (30, 1);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (31, 1);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (32, 6);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (33, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (34, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (35, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (36, 2);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (37, 4);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (38, 3);

INSERT INTO HOTEL_ROOMS (ROOM_NUMBER, ROOM_TYPE)
VALUES (39, 3);

